apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres-market:5432
    database: market_data
    user: ${MARKET_DB_USER}
    secureJsonData:
      password: ${MARKET_DB_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1600
    isDefault: true

  